name: Docker Compose Actions Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker Compose
        run: |
          docker-compose up -d

      - name: Show running Docker containers
        run: docker ps

      - name: Run tests
        run: |
          # Add any commands to test your application here

      - name: Bring Docker Compose down
        run: docker-compose down
